name: Python package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        # We test only the minimum and the maximum supported versions of python
        python-version: ["3.8", "3.11"]
        pandas-version: ["1.5", "2.1"]
        exclude:
        - python-version: "3.8"
          pandas-version: "2.1"

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas~=${{ matrix.pandas-version }}
        pip install -e '.[dev]'
    - name: Ruff Ruff
      run: |
        ruff ./src ./tests
    - name: mypy check
      run: |
        mypy ./src ./tests
    - name: Test with pytest
      run: |
        pytest
